### ISSUE TITLE
The solve efficiency of the C++ interface is lower than that of the matlab

### ISSUE THREAD

**Issue by sucrozzg** [qpSWIFT/qpSWIFT#4]
In recent use, I found that the solve efficiency of the c++ interface is much lower than that of matlab. I did a comparative experiment with the open source RF_MPC, which is solved by matlab,  and the c++ QP problem constructed in our project.In RF_MPC, I set the robot to take a trot gait and set the horizon to 10. Matlab spent 1.5ms to solve this QP problem with 240 variables, 240 inequality constrains, and 120 equality constrains. I constructed another QP problem with 180 variables, 120  inequality constrains, and 120 equality constrains in the C++ project. However, it takes more than 10ms for the computer to solve the QP problem. And occasionally the phenomenon of Maximum Iterations reached occurs during the solving process. What is the reason for this? I want to ask for your help. In addition, when qpSWIFT is called in a c++ project, the parameters are all used in Eigen form matrix. Could this be one of the reasons?
![matlab solve](https://user-images.githubusercontent.com/104248364/164909286-c312188b-3433-4db9-b624-7409d8739356.png)
![C++QProblem](https://user-images.githubusercontent.com/104248364/164909289-97c42cec-ebfb-44c5-892b-ddf683a76c7f.png)
![dense_form_solve_time](https://user-images.githubusercontent.com/104248364/164909291-cb4ddf4f-56eb-4e12-a27c-3ec613bcc70a.png)
![sparse_form_solve_time](https://user-images.githubusercontent.com/104248364/164909295-0ca441ce-44ec-4be7-a987-09bb82e6bd4d.png)

**Comment by abhishek-pandala** [comment]
Hi sucrozzg, Thank you for your interest in our solver. As per your question, I have the following suggestions
1) I am not sure how the cpp interface is slower than Matlab. The mex file in matlab calls the cpp interface itself. So I believe there should be some problem with your cpp code. Is the cpp code being run in debug mode? Also are the inputs (dimensions of matrices, number of constraints, etc) given to the qpSWIFT solver in the correct format ?
2) Since the problems you are comparing in matlab and cpp are different, I am wondering if the input matrices provided in the cpp interface are more dense than the ones used in matlab. qpSWIFT performs sparse LDL decomposition and the performance of the solver heavily depends on the sparsity pattern of the input matrices. Have you checked the solve time for RF_MPC using cpp interface ?
3) qpSWIFT does not perform infeasibility detection and hence any infeasible problem is likely to hit the maximum number of iterations. In addition, max iterations are also reached when the input matrices are ill-conditioned. Check to see if these issues arise in your code.

**Comment by sucrozzg** [comment]
Thank you, professor. Based on your suggestion, I re-installed qpSWIFT following the tutorial on GitHub. This worked well. The solving time of the CPP interface has reached the same level as Matlab. I think maybe there is some omission in my previous installation steps. This is a good product. Thank you!
